export const ALL_CHECKED = 'ALL_CHECKED';
export const UN_CHECKED_ALL = 'UN_CHECKED_ALL';
export const TOGGLE_CHECK = 'TOGGLE_CHECK';

export const GET_SEARCH_ID = 'GET_SEARCH_ID'
export const TICKETS_LOAD = 'TICKETS_LOAD';

export const FILTER_TICKET = 'FILTER_TICKET';

export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const NO_TICKETS_FOUND = 'NO_TICKETS_FOUND';

export const CHEAPEST_TICKETS = 'CHEAPEST_TICKETS';

export const FIVE_TICKETS = 'FIVE_TICKETS';
